// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCgWa8DcOokLRhI8Ml5SSmkLsAHymoiWb8',
    appId: '1:374692309890:web:1d1fff4571e95b41d7fd9b',
    messagingSenderId: '374692309890',
    projectId: 'disastermgmnt',
    authDomain: 'disastermgmnt.firebaseapp.com',
    storageBucket: 'disastermgmnt.firebasestorage.app',
    measurementId: 'G-TS1V3278V9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAAxhvVG3UkHcy3eqJ59RToup_QRGNPzak',
    appId: '1:374692309890:android:62a81f56a19d833cd7fd9b',
    messagingSenderId: '374692309890',
    projectId: 'disastermgmnt',
    storageBucket: 'disastermgmnt.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQbLrEB72tNgU45kNVFqhCUK8WI1nuP2Y',
    appId: '1:374692309890:ios:faf6b17e05a1e9c9d7fd9b',
    messagingSenderId: '374692309890',
    projectId: 'disastermgmnt',
    storageBucket: 'disastermgmnt.firebasestorage.app',
    iosBundleId: 'com.disasterapp.disasterManagementApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQbLrEB72tNgU45kNVFqhCUK8WI1nuP2Y',
    appId: '1:374692309890:ios:faf6b17e05a1e9c9d7fd9b',
    messagingSenderId: '374692309890',
    projectId: 'disastermgmnt',
    storageBucket: 'disastermgmnt.firebasestorage.app',
    iosBundleId: 'com.disasterapp.disasterManagementApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCgWa8DcOokLRhI8Ml5SSmkLsAHymoiWb8',
    appId: '1:374692309890:web:a253db9e86619015d7fd9b',
    messagingSenderId: '374692309890',
    projectId: 'disastermgmnt',
    authDomain: 'disastermgmnt.firebaseapp.com',
    storageBucket: 'disastermgmnt.firebasestorage.app',
    measurementId: 'G-86JLWZY3V5',
  );
}
